GettingStarted/Setup.md, Turtlebot/Turtlebot3.md
Please let me know if the link I added was not the original intention. Currently it's a 404
=> Fix setup link & path

Build/rosdeps_vcpkg.md
This is a doc still in progress.
=> Add vcpkg, rosdeps, and Azure DevOps CI integration draft

Porting/ms-iot_payload.md
Break them down to different tiers so we know what to upstream first.
=> Reorganize changes list.

Build/buildfarm.md
Update the document to reflect the current status.
=> Update BuildFarm documentation

Porting/ms-iot_payload.md
Removed the repositories upstream'ed.
=> Removed forked repositories which are upstream'ed

CODEOWNERS, README.md, mkdocs.yml
* Adding README.md to show how to test the pages locally.
* Adding CODEOWNERS to add the correct team for pull requests.
* Fixing the `edit_uri` to reflect the correct branch in use.
=> Adding README.md and CODEOWNERS

docs/GettingStarted/AddingVCPKG.md, docs/GettingStarted/NewToROS.md, docs/GettingStarted/PortingANode.md, docs/GettingStarted/SetupCI.md, docs/GettingStarted/Troubleshooting.md, docs/GettingStarted/UsingROSonWindows.md, docs/GettingStarted/UsingVCPKG.md, docs/Moveit/UR3.md, docs/Moveit/moveit_tutorials.md, docs/Porting/Cookbook.md, docs/ROSAtMS/ROS1AzureVM.md, docs/ROSAtMS/WinML.md, docs/WhatsNew.md, docs/index.md, mkdocs.yml
=> Doc Refresh

azure-pipelines.yml, docs/GettingStarted/PortingANode.md, docs/GettingStarted/UsingROSonWindows.md, docs/Turtlebot/Turtlebot3.md, docs/tutorials/sick_s300/getting_started.md, mkdocs.yml
* Fixed broken links.
* Explicit to set [strict](https://www.mkdocs.org/user-guide/configuration/#strict) mode to build the doc.
* Add pull request CI pipeline as check-in gates.
=> Fixed broken links

docs/GettingStarted/Troubleshooting.md, docs/ROSAtMS/ROS1AzureVM.md, docs/ROSAtMS/WinML.md, docs/Turtlebot/Turtlebot3.md, docs/tutorials/sick_s300/getting_started.md
* MkDocs style fixes.
* Fix `cob_sick_s300` repository path.
* Normalize `TurtleBot` wording usage.
=> MkDocs style fixes.

docs/Build/buildfarm.md
* Adding `noetic` , `eloquent` and `foxy`.
=> updated the build badges.

docs/GettingStarted/UsingROSonWindows.md
* defined an example scripts how to consume a package by using ROS workspace tools.
* adding a few good resource links regarding to package information.
=> updated `Using a ROS Package on Windows`

docs/Porting/Cookbook.md
Add documentation for autologon and starting a roslaunch on logon.
=> add autologon

mkdocs.yml
Adding the paid support link to the docs
=> Adding the support link to the docs page

docs/tutorials/peak/peak.md, mkdocs.yml
=> Adding PCAN-Basic tutorial

docs/GettingStarted/AzureSetupCD.md, docs/GettingStarted/GithubSetupCD.md
Add a statement on creating a chocolatey mapping for a chocolatey package.
=> Add section on mapping chocolatey

docs/GettingStarted/UsingROSonWindows.md
=> Fix typo in UsingROSonWindows

docs/GettingStarted/GithubSetupCS_Windows_Nav2.md, docs/GettingStarted/SetupRos2.md, docs/ros2/nav2.md, docs/ros2/navigation2_foxy.repos, docs/ros2/system_tests.md, mkdocs.yml
* Added Nav2 System Tests example with GitHub runner.
* Updated the ROS 2 installation instructions to `Foxy`.
=> Adding GitHub Nav2 System Tests.

mkdocs.yml
It turned out the deployment didn't go well, so I am reverting the theme change first.
=> Revert the theme change.

README.md, azure-pipelines.yml, docs/Advanced/Performance.md, docs/Build/fromsource.md, docs/Build/source.md, docs/GettingStarted/AddingVCPKG.md, docs/GettingStarted/AzureSetupCD.md, docs/GettingStarted/AzureSetupCS_Windows.md, docs/GettingStarted/GithubSetupCD.md, docs/GettingStarted/GithubSetupCS_Windows.md, docs/GettingStarted/GithubSetupCS_Windows_Nav2.md, docs/GettingStarted/PortingANode.md, docs/GettingStarted/SetupRos2.md, docs/GettingStarted/Troubleshooting.md, docs/GettingStarted/UsingROSonWindows.md, docs/GettingStarted/UsingVCPKG.md, docs/Moveit/UR3.md, docs/Moveit/moveit_tutorials.md, docs/Porting/Cookbook.md, docs/ROSAtMS/WinML.md, docs/Turtlebot/Turtlebot3.md, docs/ros2/nav2.md, docs/ros2/system_tests.md, docs/tutorials/ethercat/soem.md, docs/tutorials/peak/peak.md, docs/tutorials/sick_s300/getting_started.md, mkdocs.yml
* Adding syntax highlighting for batch script code blocks.
* Fixed TurtleBot3 page TOC.
* Fixed the letter case for brand or product names.
=> Adding syntax highlighting & misc

docs/Moveit/moveit_tutorials.md
Use the tabbed features to add the Noetic specific instructions.
=> Updated the MoveIt docs with Noetic release.

docs/Turtlebot/Turtlebot3.md, docs/Turtlebot/turtlebot3_demo.launch, docs/Turtlebot/turtlebot3_ros1.repos
* Adding `Noetic` section.
* Using the upstream turtlebot3 example code.
=> Update turtlebot3 doc.

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, docs/Build/status.md, requirements.txt
* Update the CI badge.
* Add `devcontainer` as another way to do the local testing.
=> Update the CI badge.

docs/GettingStarted/AddingVCPKG.md
Change location of vcpkg for latest isolated release.
=> Change location of vcpkg
